[package]
name = "rust_programming_language"
version = "0.1.0"
edition = "2021"
authors = ["Simone Rosani"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
